tasks:
  - name: init
    init: npm install
    command: npm run ganache
  - name: tests
    command: |
      gp await-port 8545
      npx truffle test
    openMode: tab-after
  - name: coverage
    command: |
      npx truffle run coverage
    openMode: tab-after