tasks:
  - name: init
    init: npm install && gp sync-done initDone
    command: npm run ganache
  - name: tests
    command: |
      gp await-port 8545
      npx truffle test
    openMode: tab-after
  - name: coverage
    init: gp sync-await initDone
    command: |
      npx truffle run coverage
    openMode: split-right